apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: international-center-config
spec:
  # Tracing configuration
  tracing:
    samplingRate: "0.1"
    otel:
      endpointAddress: "http://tempo:4318/v1/traces"
      protocol: http
  
  # Metrics configuration
  metric:
    enabled: true
    http:
      enabled: true
      port: 9090
      path: "/metrics"
  
  # Logging configuration  
  logging:
    level: "info"
    
  # API configuration
  api:
    allowed:
      - name: "state"
        version: "v1"
        protocol: "http"
      - name: "pubsub"
        version: "v1"
        protocol: "http"
      - name: "bindings"
        version: "v1"
        protocol: "http"
      - name: "invoke"
        version: "v1"
        protocol: "http"
      - name: "secrets"
        version: "v1"
        protocol: "http"
      - name: "health"
        version: "v1"
        protocol: "http"
      - name: "metadata"
        version: "v1"
        protocol: "http"
  
  # HTTP pipeline configuration - temporarily disabled for GREEN phase
  # httpPipeline:
  #   handlers:
  #     - name: "cors"
  #       type: "middleware.http.cors"
  #     - name: "ratelimit"
  #       type: "middleware.http.ratelimit"
  #     - name: "oauth2"
  #       type: "middleware.http.oauth2"
  #     - name: "opa"
  #       type: "middleware.http.opa"

  # Access control configuration
  accessControl:
    defaultAction: "deny"
    trustDomain: "international-center"
    policies:
      - appId: "services-api"
        defaultAction: "allow"
        trustDomain: "international-center"
        namespace: "default"
      - appId: "content-api"
        defaultAction: "allow"
        trustDomain: "international-center"
        namespace: "default"
      - appId: "public-gateway"
        defaultAction: "allow"
        trustDomain: "international-center"
        namespace: "default"
      - appId: "admin-gateway"
        defaultAction: "allow"
        trustDomain: "international-center"
        namespace: "default"

  # Component configuration
  components:
    deny:
      - "*"
    allow:
      - "statestore"
      - "pubsub"
      - "bindings"
      - "secretstore"

  # Feature configuration
  features:
    - name: "ServiceInvocation"
      enabled: true
    - name: "StateManagement"
      enabled: true
    - name: "PubSub"
      enabled: true
    - name: "Bindings"
      enabled: true
    - name: "SecretStore"
      enabled: true
    - name: "Observability"
      enabled: true