apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://tempo:9411/api/v2/spans
  metrics:
    enabled: true
  mtls:
    enabled: false
    allowedClockSkew: 15m
    workloadCertTTL: 24h
  secrets:
    scopes:
      - storeName: secretstore-vault
        defaultAccess: allow
        allowedSecrets: ["db-password", "api-key", "jwt-secret", "api-token", "oauth2-client", "oauth2-service-client"]
  api:
    allowed:
      - name: state
        version: v1.0
        protocol: http
      - name: pubsub
        version: v1.0
        protocol: http
      - name: bindings
        version: v1.0
        protocol: http
      - name: secrets
        version: v1.0
        protocol: http
      - name: invoke
        version: v1.0
        protocol: http
  accessControl:
    defaultAction: allow
    scopes:
      pubsub-redis:
        - services-api
        - content-api
        - public-gateway
        - admin-gateway
      statestore-postgresql:
        - services-api
        - content-api
        - public-gateway
        - admin-gateway