apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://guest:guest@rabbitmq:5672/"
  - name: protocol
    value: "amqp"
  - name: hostname
    value: "rabbitmq"
  - name: username
    value: "guest"
  - name: password
    value: "guest"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: deliveryMode
    value: "0"
  - name: requeueInFailure
    value: "false"
scopes:
- content-api
- inquiries-api
- notification-api
- services-api
- public-gateway
- admin-gateway