apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://vault:8200"
  - name: vaultToken
    value: "development"
  - name: vaultKVPrefix
    value: "secret"
  - name: vaultKVUsePrefix
    value: "true"
  - name: enginePath
    value: "secret"
  - name: vaultValueType
    value: "text"
scopes:
- content-api
- inquiries-api
- notification-api
- services-api
- public-gateway
- admin-gateway