apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-postgresql
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=postgresql user=postgres password=development dbname=international_center port=5432 sslmode=disable TimeZone=UTC"
  - name: tableName
    value: "dapr_state_store"
  - name: metadataTableName
    value: "dapr_state_store_metadata"
  - name: timeout
    value: "20s"
  - name: cleanupIntervalInSeconds
    value: "3600"
scopes:
- services-api
- content-api
- public-gateway
- admin-gateway