apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://localhost:4317"
  metric:
    enabled: true
  api:
    allowed:
      - name: "state"
        version: "v1.0"
        protocol: "http"
      - name: "pubsub"
        version: "v1.0"
        protocol: "http"
      - name: "bindings"
        version: "v1.0"
        protocol: "http"
      - name: "secrets"
        version: "v1.0"
        protocol: "http"
      - name: "invoke"
        version: "v1.0"
        protocol: "http"
  middleware:
    http:
      - name: cors
        spec:
          allowedOrigins: ["*"]
          allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowedHeaders: ["*"]
      - name: rateLimiter
        spec:
          maxRequestsPerSecond: 1000
  components:
    deny:
      - name: "kubernetes"
        type: "secretstores.kubernetes"